version: '3.9'
services:
  db:
    image: postgis/postgis:15-3.4-alpine
    container_name: db_demo
    command: postgres -c 'max_connections=250'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cologne_lod2
    volumes:
      - ./cologne_lod2/cologne_lod2.sql.gz:/docker-entrypoint-initdb.d/cologne_lod2.sql.gz
    tmpfs:
      - /var/lib/postgresql/data

  ldproxy:
    image: iide/ldproxy:next 
    container_name: ldproxy_demo
    ports:
      - "7080:7080"
    volumes:
      - .:/ldproxy/data
    depends_on:
      - db
    environment:
      - EXTERNAL_URL=http://localhost:7080/rest/services
      - ENABLE_ZOOMSTACK=false
      - ENABLE_COLOGNE=false
      # Enable the following variable, if the cologne_lod2 data is available in a separate PostgreSQL instance;
      # in this case comment out "#/services/db" and "#/services/ldproxy/depends_on"
      # - DB_HOST=host.docker.internal
